# Generated by Django 2.1.7 on 2021-07-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_auto_20210629_1513'),
        ('policyBaazar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('current_doctor', models.CharField(max_length=100)),
                ('date_visit', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='home_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_line1', models.CharField(max_length=100)),
                ('add_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('area', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='life_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('health_issue', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='mobile_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('purchasing_date', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='policy_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_date', models.DateField(auto_now=True)),
                ('placedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Insurance_Policy')),
            ],
        ),
        migrations.CreateModel(
            name='travel_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelling_to', models.CharField(max_length=100)),
                ('start_Date', models.CharField(max_length=50)),
                ('End_Date', models.CharField(max_length=50)),
                ('passengers', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=100)),
                ('chassis_no', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyBaazar.UserProfile')),
            ],
        ),
    ]
